name: jupyter-forward-dev
channels:
  - conda-forge
dependencies:
  - fabric
  - jupyterlab
  - numpydoc
  - paramiko
  - pip
  - pre-commit
  - pytest
  - pytest-cov
  - rich
  - typer
  - pip:
      - git+https://github.com/Textualize/rich
      - git+https://github.com/tiangolo/typer
      - -e ../
