name: jupyter-forward-dev
channels:
  - conda-forge
dependencies:
  - codecov
  - fabric
  - numpydoc
  - paramiko
  - pip
  - pre-commit
  - pytest
  - pytest-cov
  - rich
  - typer
  - pip:
      - -e ../
