name: jupyter-forward-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - myst-nb
  - pip
  - python=3.8
  - sphinx-book-theme >= 0.0.38
  - sphinx-copybutton
  - sqlalchemy==1.3.12
  - pip:
      - sphinxext-opengraph
      - sphinx-comments
      - -r ../requirements.txt
      - -e ..
